### ISSUE TITLE
Support for Access-Control-Allow-Credentials header

### ISSUE THREAD

**Issue by shen-tian** [r0man/ring-cors#14]
As far as I can tell, this library doesn't support the `Access-Control-Allow-Credentials` header (it doesn't support `Access-Control-Expose-Headers` and `Access-Control-Max-Age` either). 

Is this a design decision, or are you open to contributions to add these?

**Comment by r0man** [comment]
@shen-tian Take a look at the tests. This should work.
https://github.com/r0man/ring-cors/blob/master/test/ring/middleware/cors_test.clj#L150

**Comment by shen-tian** [comment]
Aha. That works. Thanks!
