### ISSUE TITLE
Remove dependency on ring-core

### ISSUE THREAD

**Issue by jeluard** [r0man/ring-cors#19]
`ring-cors` depends on `ring-core` for the sole method [get-header](https://github.com/ring-clojure/ring/blob/ecf06c142ee4195756f94b780c238f3a917b3b8d/ring-core/src/ring/util/response.clj#L183).

It would be nice to drop this dependency and simply copy the code in `ring-cors` for 2 reasons:

* it reduces potential for versions conflict on `ring-core`
* `ring-core` ships with lots of irrelevant transitive dependencies

What do you think? I can create a PR if needed.

**Comment by r0man** [comment]
@jeluard Yes, we can do that. PR welcome!
